Revert of Add documentation to 2 DeprecatedPaintLayer objects (patchset #2 id:20001 of https://codereview.chromium.org/1327483003/ )
Reason for revert:
Speculative revert: Failed build job.

I don't know why a comment would cause a breakage but the build output shows: 

In file included from ../../third_party/WebKit/Source/core/paint/DeprecatedPaintLayer.h:50:0,
                 from ../../third_party/WebKit/Source/core/layout/svg/LayoutSVGModelObject.cpp:39:
../../third_party/WebKit/Source/core/paint/DeprecatedPaintLayerClipper.h:135:1:error: multi-line comment [-Werror=comment]
 //                /    \
 ^

Original issue's description:
> Add documentation to 2 DeprecatedPaintLayer objects
> 
> Added class level comments to DeprecatedPaintLayerClipper
> and DeprecatedPaintLayerStackingNode.
> 
> While touching DeprecatedPaintLayerStackingNode, added a comment
> about NormalFlowChildren.
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=201805

TBR=eae@chromium.org,mstensho@opera.com,wkorman@chromium.org,jchaffraix@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1312203004

git-svn-id: svn://svn.chromium.org/blink/trunk@201809 bbb929c8-8fbe-4397-9dbb-9b2b20218538